global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter-mon'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'SRV-MON-01'

  - job_name: 'node-exporter-web'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'SRV-WEB-01'

  - job_name: 'node-exporter-db'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'SRV-DB-01'

  - job_name: 'node-exporter-mgt'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'SRV-MGT-01'
